/*
 * This source file was generated by the Gradle 'init' task
 */
package org.chess;

import org.chess.domain.board.Board;
import org.chess.console.Input;

public class App {

    private static final int SRC = 0;
    private static final int DEST = 1;

    public static void main(String[] args) {
        Input input = new Input();
        Board board = new Board();

        if (!input.suggestGame()) {
            return;
        }

        board.initialize();
        board.print();
        while (true) {
            String[] moves = input.getMoves();
            board.move(moves[SRC], moves[DEST]);
            board.print();
        }
    }

}
