/*
 * This source file was generated by the Gradle 'init' task
 */
package org.chess;

import org.chess.domain.board.Board;
import org.chess.console.Input;

public class App {

    public static void main(String[] args) {
        Input input = new Input();
        Board board = new Board();

        if (!input.suggestGame()) {
            return;
        }

        board.initialize();
        board.print();
    }

}
