/*
 * This source file was generated by the Gradle 'init' task
 */
package org.mdir;

import javax.swing.*;

public class App {

    public static void main(String[] args) {
        FileHandler fileHandler = new FileHandler();
        SwingUtilities.invokeLater(() -> {
            EditorFrame frame = new EditorFrame(fileHandler);
            frame.setVisible(true);
        });
    }

}
